name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "jrgarciadev@gmail.com"
        git config --global user.name "Junior Garcia"

    - name: Install dependencies
      shell: bash
      run: pnpm install
