# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - 📌 pin
  - security
  - accessibility
  - performance
  - documentation
  - good first issue
  - "help wanted"
  - "help wanted: high priority"
  - "help wanted: urgent"
  - "feature request"
# Label to use when marking an issue as stale
staleLabel: 'type: stale'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hello 👋, to help manage issues we automatically close stale issues.
  This issue has been automatically marked as stale because it has not had activity for quite some time.
  Has this issue been fixed, or does it still require the community's attention?
  > This issue will be closed in 10 days if no further activity occurs.
  Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Closing this issue after a prolonged period of inactivity. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
only: issues