language: "en"
early_access: false
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
      enabled: true
      ignore_title_keywords:
        - "WIP"
        - "DO NOT MERGE"
        - 'ci(changesets)'
        - 'chore(deps)'
      drafts: false
      base_branches:
        - "main"
        - "canary"
        - "fix/.*"
        - "chore/.*"
        - "feat/.*"
chat:
  auto_reply: true        
