import {tv, VariantProps} from "tailwind-variants";

export const shopCartStyles = tv({
  slots: {
    wrapper: "overflow-visible h-auto lg:h-[240px] dark:border-transparent",
    imageWrapper: [
      "flex-none",
      "w-full",
      "sm:w-48",
      "h-48",
      "mb-6",
      "sm:mb-0",
      "relative",
      "z-10",
      "before:absolute",
      "before:top-0",
      "before:left-0",
      "before:w-full",
      "before:h-full",
      "before:bg-gradient-to-br",
      "transition-all",
      "!ease-soft-spring",
      "!duration-500",
      "will-change-auto",
      "before:transition-all",
    ],
    img: [
      "overflow-visible",
      "sm:scale-125",
      "absolute",
      "z-10",
      "top-2",
      "sm:left-2",
      "inset-0",
      "w-full",
      "h-full",
      "object-cover",
      "rounded-lg",
      "transition-all",
      "will-change-auto",
      "!ease-soft-spring",
      "!duration-300",
    ],
    contentWrapper: "flex flex-col justify-center transition-all h-full h-[200px]",
    title: ["relative", "w-full", "flex-none", "text-xl", "font-semibold", "text-foreground"],
    description: ["my-2", "w-full", "text-base", "text-neutral-500"],
    price: "relative text-lg font-semibold text-foreground",
    previousPrice: "relative line-through font-semibold text-neutral-400 ml-3",
    percentOff: "relative font-normal text-success ml-3",
    sizeOption: [
      "w-8",
      "h-8",
      "flex",
      "m-0",
      "justify-center",
      "items-center",
      "text-sm",
      "rounded-full",
    ],
    buyButton: ["text-sm", "font-normal"],
    addToBagButton: ["text-sm", "font-normal"],
    starButton: "absolute top-3 right-3 text-neutral-400 data-[liked=true]:text-warning",
  },
  variants: {
    theme: {
      nextui: {
        card: "py-5",
        imageWrapper: ["before:rounded-2xl", "before:from-[#010187] before:to-[#18000E]"],
        sizeOption: [
          "group-data-[checked=true]:bg-primary",
          "group-data-[checked=true]:text-primary-foreground",
        ],
      },
      modern: {
        wrapper: "rounded-3xl",
        contentWrapper: "ml-3",
        imageWrapper: [
          "lg:scale-[1.3]",
          "before:rounded-3xl",
          "before:from-[#870172] before:to-[#18000E]",
          "shadow-lg",
        ],
        img: "sm:scale-90 sm:left-0",
        title: "text-2xl",
        description: "text-sm",
        sizeOption: [
          "group-data-[checked=true]:bg-secondary",
          "group-data-[checked=true]:text-secondary-foreground",
        ],
        percentOff: "text-pink-500",
        buyButton: ["bg-secondary", "text-sm", "font-normal", "rounded-full"],
        addToBagButton: [
          "border-secondary",
          "text-secondary",
          "text-sm",
          "font-normal",
          "rounded-full",
        ],
      },
      elegant: {
        wrapper: "rounded-md",
        contentWrapper: "ml-3",
        imageWrapper: [
          "lg:scale-[1.3]",
          "before:rounded-md",
          "before:from-[#323232] before:to-[#000000]",
          "shadow-xl",
        ],
        img: "sm:scale-75 sm:left-0 saturate-0",
        title: "text-xl font-mono font-thin",
        description: "text-sm font-mono font-light",
        sizeOption: [
          "group-data-[checked=true]:bg-foreground",
          "group-data-[checked=true]:text-background",
        ],
        price: "font-mono font-thin",
        previousPrice: "font-mono font-light ml-2",
        percentOff: "text-neutral-500 font-mono text-sm",
        buyButton: ["bg-foreground", "text-background", "text-sm", "font-normal", "rounded-sm"],
        addToBagButton: [
          "border-foreground",
          "text-foreground",
          "text-sm",
          "font-normal",
          "rounded-sm",
        ],
      },
      retro: {
        wrapper: "bg-[#F4E8D1] dark:bg-[#E1CA9E] rounded-sm",
        contentWrapper: "ml-3",
        imageWrapper: [
          "before:rounded-none",
          "before:from-[#FFD34E] before:to-[#EE457E]",
          "before:shadow-md",
          "after:-z-10",
          "after:absolute",
          "after:top-2",
          "after:left-2",
          "after:w-full",
          "after:h-full",
          "after:bg-[#FFD34E]",
        ],
        img: "sm:scale-125",
        title: "text-xl uppercase text-black",
        description: "text-[0.7rem] uppercase text-black",
        sizeOption: [
          "text-black/80",
          "group-data-[checked=true]:bg-[#EE457E]",
          "group-data-[checked=true]:text-white",
        ],
        price: "text-black",
        previousPrice: "text-black/60 ml-2",
        percentOff: "text-black/40 font-mono text-sm",
        buyButton: [
          "bg-[#FFD34E]",
          "text-black",
          "font-medium",
          "uppercase",
          "text-sm",
          "rounded-sm",
        ],
        addToBagButton: [
          "border-[#FFD34E]",
          "text-black",
          "uppercase",
          "font-medium",
          "text-sm",
          "rounded-sm",
        ],
      },
    },
  },
  defaultVariants: {
    theme: "nextui",
  },
});

export type ShopCartProps = VariantProps<typeof shopCartStyles>;
